version: '2'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=clinic
      - POSTGRES_USER=cuba
      - POSTGRES_PASSWORD=cuba
    ports:
      - "5432:5432"
  web:
    depends_on:
      - postgres
    image: clinic
    ports:
      - "8080:8080"